#!/usr/bin/env bash

if [[ -n ${1} ]]
then

    exec ${@}

else

    echo fastqtools v0.8
    echo ===============
    echo the following commands are available:
    ls -1 ${FASTQTOOLS_HOME}/bin
    echo
    echo "Usage:"
    echo "singularity run --app bioinformatics-fastqtools ${SINGULARITY_CONTAINER} <command>"
    echo

fi
